"""Add views column to Post

Revision ID: 01b3eec5c2f2
Revises: 172df50bb0d1
Create Date: 2025-02-28 17:39:43.043088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b3eec5c2f2'
down_revision: Union[str, None] = '172df50bb0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('likes', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'])
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'likes')
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###
